---
title: "lauren-vignette-file"
output: 
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lauren-vignette-file}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: sample.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.width = 5,
  fig.retina = 2,
  comment = "#>")
knitr::read_chunk("my-external-code.R")
```

# Let's load our library

```{r setup}
library(mysimplecompendium)
mysimplecompendium::hello()
```

# Let's make some plots

```{r starwars-gender-plot, fig.cap="Gender of Starwars Characters"}
library(tidyverse)

starwars %>%
  mutate(gender_fct = fct_infreq(gender)) %>%
  ggplot(aes(gender_fct)) +
  geom_bar() + 
  xlab("") + theme_minimal(base_size = 14)
```

```{r, starwars-plot, fig.cap = "A ggplots of starwars stuff"}
library(tidyverse)

starwars %>% filter(species == "Human") %>% ggplot() + aes(x = height, y = mass) + geom_point()

```

In Figure \@ref(fig:starwars-gender-plot) we can see there is an imbalance of gender ratios.


# Let's Run Some External Code
```{r set-up-the-data, eval = FALSE}

```

```{r set-up-and-print-the-data, echo = FALSE}
<<set-up-the-data>>
<<print-the-data>>

```

```{r plot-the-data, echo = FALSE}

```


See @campos2015zika for more information on the zika virus!

# References cited


